
title: "Pierre Brasseur | Sociologue"
email: "pierre.brasseur@ulb.be"
description:  Sociologue 
twitter_username: p_brasseur
github_username: brasseurp
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
# timezone: MC

include:
  - _pages

exclude: 
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Pierre Brasseur"
  avatar : "/_data/bio-photo.jpg"
  bio    : "Sociologue"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://pierrebrasseur.fr"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/p_brasseur"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brasseurp"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pierrehenriiiii"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/p_brasseur"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/brasseurp"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/pierrehenriiiii"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true

  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      toc: true


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
